### ISSUE TITLE
[Feature Request] Declare a fallback unit in case it's missing from the query

### ISSUE THREAD

**Issue by CatchABus** [tbjgolden/media-query-fns#5]
I started using this package and I'm very happy with your work!
I'm trying to use it for implementing media queries in [NativeScript](https://nativescript.org). There, we can set values like width and height with or without specifying unit:

```css
.title {
  font-size: 32;
  width: 200;
}
```

I'd like to use media queries the same way by specifying a default unit of my choice in case it's missing from the query.
```css
@media only screen and (max-width: 600) {
  body {
    background-color: lightblue;
  }
}
```

I imagine something like this:
```js
const testEnv = (widthPx = 1280, heightPx = 800) => ({
  widthPx,
  heightPx,
  deviceWidthPx: widthPx,
  deviceHeightPx: heightPx,
  dppx: 2,
  fallbackUnit: 'px' // Use this in case unit is not specified
});
console.log(matches(maxWidthQuery, testEnv(1280))); // false
```
